import Head from 'next/head'
import {
  ConnectPage,
} from '@/components/WalletConnection'
import { ReactElement } from 'react'
import { useIsConnected } from '@/contexts/Beacon'
import MainLayout from '@/layout/MainLayout'
import { useRouter } from 'next/router'

export default function Home() {
  const isConnected = useIsConnected()
  const router = useRouter()

  if (isConnected()) {
    router.push('/create')
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ConnectPage />
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <MainLayout>{page}</MainLayout>
}