import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import {
  ConnectCtx,
  ConnectModal,
  ConnectPage,
} from '@/components/WalletConnection'
import CreateNFT from '@/components/CreateNFT'
import MintSuccess from '@/components/MintSuccess'
import { useContext, useEffect, useState } from 'react'
import { useIsConnected } from '@/contexts/Beacon'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const connectCtx = useContext(ConnectCtx)
  const isConnected = useIsConnected()
  const [stage, setStage] = useState<'connect' | 'create' | 'success'>(
    'connect'
  )

  const setMintSuccess = () => {
    setStage('success')
  }
  useEffect(() => {
    if (isConnected()) {
      setStage('create')
    } else {
      setStage('connect')

    }
    console.log(isConnected())
  }, [isConnected])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-dm-sans">
        <Header />
        {stage === 'connect' && <ConnectPage />}
        {stage === 'create' && <CreateNFT proceed={setMintSuccess} />}
        {stage === 'success' && <MintSuccess />}
      </main>
      <ConnectModal />
    </>
  )
}
